apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-site
  labels:
    app: my-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-site
  template:
    metadata:
      labels:
        app: my-site
    spec:
      containers:
        - name: my-site
          image: alexjohnwilkinson/my-site:init
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: url
              value: http://alexwilkinson.com
