export const FETCH_PORTFOLIO_LIST = 'FETCH_PORTFOLIO_LIST';
export type FETCH_PORTFOLIO_LIST = typeof FETCH_PORTFOLIO_LIST;

export const FETCHING_PORTFOLIO_LIST = 'FETCHING_PORTFOLIO_LIST';
export type FETCHING_PORTFOLIO_LIST = typeof FETCHING_PORTFOLIO_LIST;

export const FETCHED_PORTFOLIO_LIST = 'FETCHED_PORTFOLIO_LIST';
export type FETCHED_PORTFOLIO_LIST = typeof FETCHED_PORTFOLIO_LIST;
