export const GET_BLOG_LIST = 'GET_BLOG_LIST';
export type GET_BLOG_LIST = typeof GET_BLOG_LIST;

export const FETCH_BLOG_LIST = 'FETCH_BLOG_LIST';
export type FETCH_BLOG_LIST = typeof FETCH_BLOG_LIST;

export const FETCHING_BLOG_LIST = 'FETCHING_BLOG_LIST';
export type FETCHING_BLOG_LIST = typeof FETCHING_BLOG_LIST;

export const FETCHED_BLOG_LIST = 'FETCHED_BLOG_LIST';
export type FETCHED_BLOG_LIST = typeof FETCHED_BLOG_LIST;

export const GET_BLOG_POST = 'GET_BLOG_POST';
export type GET_BLOG_POST = typeof GET_BLOG_POST;

export const CREATE_BLOG_POST = 'CREATE_BLOG_POST';
export type CREATE_BLOG_POST = typeof CREATE_BLOG_POST;

export const UPDATE_BLOG_POST = 'UPDATE_BLOG_POST';
export type UPDATE_BLOG_POST = typeof UPDATE_BLOG_POST;

export const RELEASE_BLOG_POST = 'RELEASE_BLOG_POST';
export type RELEASE_BLOG_POST = typeof RELEASE_BLOG_POST;

export const REMOVE_BLOG_POST = 'REMOVE_BLOG_POST';
export type REMOVE_BLOG_POST = typeof REMOVE_BLOG_POST;
